[project]
name = "webmentions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Maryam Stellamaris", email = "mahid@standingpad.org" }
]
requires-python = ">=3.14"
dependencies = [
    "asqlite>=2.0.0",
    "fastapi[standard]>=0.141.1",
    "selectolax>=0.4.11",
    "slowapi>=0.1.10",
]

[project.scripts]
webmentions = "webmentions:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
